### ISSUE TITLE
BUG: method include_model does not work with model in subdirectories 

### ISSUE THREAD

**Issue by sseide** [yuki-kimoto/DBIx-Custom#7]
the method include_model() in DBIx::Custom expects the main database model to be loaded from the top level (e.g MyModel.pm). Models in sub directories does not work (e.g. SubDir::MyModel). because either the 'eval "use $name_space"' or the "$path = @INC{$name_space.pm}" fail.

tested with: 
```
 $dbi->include_model('SubDir::MyModel')
 $dbi->include_model('SubDir/MyModel')
```

A short patch for "DBIx/Custom.pm" to fix the model loading follows, but i did not thoroughly tested it for other parts where this may break...

```
803c803,805
<     my $path = $INC{"$name_space.pm"};
---
>     my $name_space_dir = $name_space;
>     $name_space_dir =~ s/::/\//g;
>     my $path = $INC{"$name_space_dir.pm"};
```

Best Regards,
Stefan Seide

**Comment by yuki-kimoto** [comment]
Fix this bug in 0.31. Sorry to wait for a long time.
